[build]
  command = "npm install"
  publish = "."
  
[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
  external_node_modules = ["sharp", "@napi-rs/canvas", "pdfjs-dist", "pdf-to-png-converter"]

[functions."pdf-crop"]
  timeout = 26
